version: "2.3"
services:
  detection-cpu:
    image: detection-cpu:latest
    container_name: detection-cpu
    build:
      context: .
      dockerfile: cpu/Dockerfile
    #runtime: nvidia
    ports:
      - 6998:80
#  detection-gpu:
#    image: detection-cpu:latest
#    container_name:  model-cpu
#    build:
#      context: .
#      dockerfile: cpu/Dockerfile
#    runtime: nvidia
#    ports:
#      - 8501:8501







