version: "2.3"
services:
  detection-cpu:
    image: detection-cpu:latest
    container_name: detection-cpu
    build:
      context: .
      dockerfile: cpu/Dockerfile
    ports:
      - 6998:80
  detection-gpu:
    image: detection-gpu:latest
    container_name:  detection-gpu
    build:
      context: .
      dockerfile: gpu/Dockerfile
    #    runtime: nvidia
    ports:
      - 6998:80







